package com;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;


public class Register extends HttpServlet {
	private static final long serialVersionUID = 1L;
    
	
    public Register() {
        super();
    }
    
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		
		try {
			
			String name=request.getParameter("uname");
			String pass=request.getParameter("upass");
			int age=Integer.parseInt(request.getParameter("uage"));
			int mbl=Integer.parseInt(request.getParameter("mbl"));
			String email=request.getParameter("email");

			
			
			
			Class.forName("com.mysql.jdbc.Driver");
			Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/dummy?autoReconnect=true&useSSL=false","root","root");
			PreparedStatement pstmt=con.prepareStatement("insert into customers (Name, Password, MobileNo, EmailID)values(?,?,?,?);");
//			ResultSet tableKeys = pstmt.getGeneratedKeys();
//			tableKeys.next();
//			int autoGeneratedID = tableKeys.getInt(1);
			//pstmt.setInt(1,autoGeneratedID);
			pstmt.setString(1,name);
			pstmt.setString(2,pass);
			pstmt.setInt(3,mbl);
			pstmt.setString(4,email);

			pstmt.executeUpdate();
			pstmt.close();
			
			
//			HttpSession session=request.getSession();
//			session.setAttribute("uname", name);
//			session.setAttribute("uage", age);
//			session.setAttribute("mbl", mbl);
//			session.setAttribute("email", email);
			
			response.sendRedirect("login.jsp");
		} catch (Exception e) {
			// TODO: handle exception
		}
		
	}

}
